set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" le plugins
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-rails.git'
Bundle 'kien/ctrlp.vim'
Bundle 'Raimondi/delimitMate'
Bundle 'scrooloose/nerdtree'
Bundle 'honza/vim-snippets'
Bundle 'ervandew/supertab'
Bundle 'scrooloose/syntastic'
Bundle 'kchmck/vim-coffee-script'
Bundle 'larssmit/vim-getafe'
Bundle 'Lokaltog/vim-powerline'
Bundle 'garbas/vim-snipmate'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'tomtom/tlib_vim'
Bundle 'chriskempson/tomorrow-theme', {'rtp': 'vim/'}
Bundle 'vim-ruby/vim-ruby'
Bundle 'ap/vim-css-color'
Bundle 'matchit.zip'
Bundle 'lunaru/vim-twig'
Bundle 'ciaranm/inkpot'
Bundle 'majutsushi/tagbar'
Bundle 'flazz/vim-colorschemes'
Bundle 'junegunn/seoul256.vim'
Bundle 'mustache/vim-mustache-handlebars'
Bundle 'tpope/vim-haml'
Bundle 'jnwhiteh/vim-golang'

" Indent
filetype plugin indent on
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab

" Mappings
let mapleader = ","
map <leader>n :NERDTreeToggle<CR>
let g:ctrlp_map = "<leader>p"
map <leader>t :TagbarToggle<CR>

" Color scheme
syntax on
colorscheme Tomorrow-Night
set guifont=Inconsolata

if has("gui_macvim")
    colorscheme Tomorrow-Night
    set guifont=Inconsolata\ XL:h13
endif

" Gui options
set guioptions-=T 
set guioptions-=r
set guioptions-=m
set go-=L
set laststatus=2
set nofoldenable

" Plugins settings
let g:NERDTreeWinPos = "right"
let g:Powerline_symbols = 'fancy'
let g:ctrlp_custom_ignore = 'node_modules\|DS_Store\|git\|cache\|vendor'

" Editor settings
set nowrap
set number

if &term =~ '256color'
  " Disable Background Color Erase (BCE) so that color schemes
  " work properly when Vim is used inside tmux and GNU screen.
  " See also http://snk.tuxfamily.org/log/vim-256color-bce.html
  set t_ut=
endif
